// Package sql2struct
// @Title 输出模版定义
// @Description 请填写文件描述（需要改）
// @Author shigx 2022/4/20 6:13 下午
package sql2struct

import "html/template"

const tpl = `// Code generated by tool-cli DO NOT EDIT
package {{.pkg}}

import "time"

// {{.structName}} {{.structComment}}
type {{.structName}} struct {
	{{- range $key, $value := .structContent}}
	{{$value | unescaped}}
	{{- end}}
}

func ({{.structName}}) TableName() string {
	return "{{.tableName}}"
}`

// GetTemplate
// @Description 返回模版
// @Auth shigx
// @Date 2022/4/20 6:25 下午
// @param
// @return
func GetTemplate() (*template.Template, error) {
	return template.New("output_template").Funcs(template.FuncMap{"unescaped": unescaped}).Parse(tpl)
}

// @Description 字符串不转译函数
// @Auth shigx
// @Date 2022/4/20 11:09 下午
// @param
// @return
func unescaped(str string) template.HTML {
	return template.HTML(str)
}
